apiVersion: apps/v1
kind: Deployment
metadata:
  name: averagestockprice
spec:
  selector:
    matchLabels:
      app: averagestockprice
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: averagestockprice
    spec:
      containers:
      - name: averagestockprice
        image: mrignayni/average-stock-price-alpine
        ports:
        - containerPort: 8080
          hostPort: 8080
